### ISSUE TITLE
Error while running autogenerated TestScripts from US Core

### ISSUE THREAD

**Issue by jhlee-mitre** [fhir-crucible/testscript-engine#36]
**Describe the bug**
Undefined error occurs while running US Core TestScripts autogenerated from the generator

**To Reproduce**
1. Clone the TestScript generator as it is in github
2. Run the generator for US core
3. Clone the TestScript engine as it is in github
4. Run the engine with TestScript folder pointing to /testscript-generator/testscripts/generated
5. See error

**Screenshots**

```
FINISHED INITIALIZING CLIENT(S).

   STARTING TO EXECUTE RUNNABLE: [AllergyIntolerance-search-type-TestScript]

      STARTING TO PREPROCESS
      FINISHED PREPROCESSING.

      STARTING TO TEST
         OPERATION EXECUTION
            GETTING: http://hapi.fhir.org/baseR4/AllergyIntolerance?_ 
            (✓) Executed Operation: [unlabeled]
         EVALUATING ASSERTION
            (✓) Response: As expected, Response equals okay. Found okay.
Traceback (most recent call last):
	17: from driver.rb:28:in `<main>'
	16: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptEngine.rb:107:in `execute_runnables'
	15: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptEngine.rb:107:in `each'
	14: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptEngine.rb:108:in `block in execute_runnables'
	13: from /Users/jaehoonlee/Documents/testscript-engine/lib/MessageHandler.rb:63:in `run'
	12: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptRunnable.rb:88:in `run'
	11: from /Users/jaehoonlee/Documents/testscript-engine/lib/MessageHandler.rb:83:in `test'
	10: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptRunnable.rb:109:in `test'
	 9: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptRunnable.rb:109:in `each'
	 8: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptRunnable.rb:109:in `block in test'
	 7: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptRunnable.rb:125:in `handle_actions'
	 6: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptRunnable.rb:125:in `each'
	 5: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestScriptRunnable.rb:130:in `block in handle_actions'
	 4: from /Users/jaehoonlee/Documents/testscript-engine/lib/MessageHandler.rb:106:in `evaluate'
	 3: from /Users/jaehoonlee/Documents/testscript-engine/lib/assertions.rb:59:in `evaluate'
	 2: from /Users/jaehoonlee/Documents/testscript-engine/lib/MessageHandler.rb:112:in `pass'
	 1: from /Users/jaehoonlee/Documents/testscript-engine/lib/TestReportHandler.rb:46:in `pass'
/Users/jaehoonlee/Documents/testscript-engine/lib/TestReportHandler.rb:196:in `pass': undefined method `result=' for nil:NilClass (NoMethodError)
```

**Comment by jhlee-mitre** [comment]
Resolved
